### ISSUE TITLE
Combining forecasts

### ISSUE THREAD

**Issue by tmerrittsmith** [business-science/sweep#7]
Having generated multiple timeseries forecasts as described in Vignette SW01, I'd like to combine the forecasts to create an overall projection. How could this be done using the output of `_fcast_tidy`, which is a tibble of tibbles containing the forecasts for each dataset? Clearly I could just sum the forecasts, but how would I go about generating a confidence interval for this sum?

**Comment by mdancho84** [comment]
Regarding forecasting confidence intervals, you might want to check out some of the packages that @topepo is working on including `rsample` and `tidyposterior`. The `rsample` package has a nice article on rolling origin resampling, which will help with confidence intervals of single or stacked model. [rsample Time Time Series Analysis Example](https://topepo.github.io/rsample/articles/Applications/Time_Series.html)

**Comment by tmerrittsmith** [comment]
Thanks @mdancho84. I've also been looking at the [hts](https://cran.r-project.org/web/packages/hts/vignettes/hts.pdf) package by Rob Hyndman, which includes some nice methods for creating hierarchical time series models. It feels like that's the natural next step with the examples and methods provided in sweep. Related to this would be the option to 'sweep' a tibble into an mts, or the tibble of tibbles or tibble of timeseries into an mts, so that hts could be implemented. I'm a bit of a noob in terms of git contributing, the broom package (as the parent of sweep) and timeseries methods in general, but would it be ok for me to try and extend sweep with some of this functionality?

**Comment by mdancho84** [comment]
HTS is good. You can read about it more in Hyndman et als book [here](https://www.otexts.org/fpp/9/4). It's just an approach that uses blended or hierarchical groups within an aggregated time series.  

I actually don't use `hts` much. The `forecast` package suits most people (including me) because it has the `arima` and `ets` functions that are most commonly used. When you get into aggregating, you normally just do a bottom-up approach / top-down with proportions, which can be done with `forecast` for each group. 

I'd recommend spending some time with `arima()` and `auto.arima()`. You can `map()` the modeling functions in the tidyverse, which is the best way to model in my opinion.

**Comment by KKulma** [comment]
a quick question to @mdancho84 : you mentioned that one can apply a  bottom-up approach / top-down with proportions with `forecast` package. Could you share any code examples/blog post where this has been done? My initial googling didn't bring anything apart from `hts` examples. Thanks!
